### ISSUE TITLE
Relative path not recognized after exporting in the 'web' format

### ISSUE THREAD

**Issue by rkttu** [LiaScript/LiaScript-Exporter#18]
When content is exported in web format, if you view the content in the subdirectory with a web browser, the relative path is not recognized and the image is not loaded properly because it changes to an absolute path.

For example, in the README.md file, add the image as follows:

```markdown
![Figure](images/image01.png)
```

The folder structure is as follows.

![image](https://user-images.githubusercontent.com/1297346/131629494-4a566b18-bd63-4909-a9ba-0239c609ed62.png)

In a real website, it tries to find the image at the root by prefixing it with a '/' character, without considering that it is a relative path as shown in the figure below. So I get a 404 error.

![image](https://user-images.githubusercontent.com/1297346/131629594-2ca11a98-da37-4fae-a9ff-f5e028ec9a23.png)

**Comment by andre-dietrich** [comment]
Hi, I see the problem ... I have to think about the way and the possibilities of how the root path of a course is determined. But you can simply fix this problem locally, for now.

You can simply overwrite the global base with the following macro, simply add `base: ./` into the main-header of your document and all images and relatives paths should use this as the root ... resulting in `./images/image01.png` ... 

``` markdown
<!--
...

base: ./

-->

# main title

```

Actually it should not interfere with future solutions, since the urls should work properly in any case ...

**Comment by rkttu** [comment]
Problem has gone. Thank you. 👍
