### ISSUE TITLE
'web' format does not work as expected

### ISSUE THREAD

**Issue by rkttu** [LiaScript/LiaScript-Exporter#24]
I tested the latest version of liascript-exporter (https://www.npmjs.com/package/@liascript/exporter/v/2.1.1--0.10.0).
When I try to publish existing liascript markdown file, static contents does not display its own content.

![image](https://user-images.githubusercontent.com/1297346/155041855-086b94ca-0c7a-41b5-abcd-78dc589f6a8c.png)

Then, I try to navigate `index.html` page, liascript throws an error.

![image](https://user-images.githubusercontent.com/1297346/155041909-1f285480-a4da-4b6e-9dc9-8999ce0f906b.png)

**Comment by rkttu** [comment]
On the contrary, older version `@liascript/exporter@1.0.51--0.9.51` works as expected.

![image](https://user-images.githubusercontent.com/1297346/155042103-f88311b6-584c-4688-91b7-fbe4f242690c.png)

**Comment by andre-dietrich** [comment]
Hi @rkttu , I just updated the exporter. The problem was that a renamed variable, which defines the course within LiaScript, was not updated within the exporter :see_no_evil: ... I just changed this and added a few more options for building web-projects ...

`--web-iframe` will hide the README, but also the Navigation via `#`

`--web-indexeddb` will store the state of your course within the browser indexeddb ... it will generate a random key for the database to store the state and updating will generate a completely new key randomly... If you think of continuous delivery, you can add a unique key to this parameter ... If you use the same, this will reuse the old states, which comes handy if you are only updating typos or add content to the end of your course ... if you restructure the entire content, you will have to use another key ...

I hope this makes sense ;-)

**Comment by andre-dietrich** [comment]
By the way, you can also use some more macros in your course:
https://github.com/liascript/liascript#Version-Changes

with `@classroom: enable` you could now also ... add the first classroom functionality to your course. If you open a Classroom, this will update the url, thus, it will only work wihout `--web-iframe`... If you then share this link, the and other open this course, the states of quizzes and surveys will be synced between all users ... still a bit experimental ... in the future we hope, to add more functionality ...

**Comment by rkttu** [comment]
Thanks for the quick troubleshooting. The function you suggested is still inconvenient to actually use for education, but I will try to use it when the function is officially released. 👍
