### ISSUE TITLE
Export contains files that prevent import

### ISSUE THREAD

**Issue by rfuehrer** [LiaScript/LiaScript-Exporter#30]
The export of a directory maintained in Github contains the directory `.git`. This contains files or. MIME types that are blocked by SCORM (here: SCORM Cloud with Scorm2004 file format). These can prevent an import and must be removed manually in the created export file before import into SCORM/LMS.

Used command:

`liaex -i README.md -o opensource -f scorm2004 --scorm-organization Dummy --scorm-typicalDuration PT0H015M0S`

![81635](https://user-images.githubusercontent.com/25303664/219969337-31f685da-8165-4e94-8adc-5d5a748c4b50.png)

The following solutions would be conceivable:
- Description of a recommended procedure that prevents the packing of unwanted or unauthorized files.
- Support of a parameter that allows the exclusion of files and directories
- support of an ignore file (for example `.liaignore`) which excludes files and directories for packing similar to a .gitignore file

**Comment by andre-dietrich** [comment]
Thanks for the report, I can confirm this and it should actually not happen. `.git` should actually be filtered and not included.

I tried this locally, this bug seems to appear, when you build the SCORM package from within the project-folder, you could try the following

`liaex --input docs/README.md --path docs --format scorm2004` 

with the `--path` or `-p` option you can define the base-path for packaging. In this case the filter seems to work and hidden folders are not included ...

However, this needs to fixed ...

**Comment by rfuehrer** [comment]
Ja, Angabe des Verzeichnisses hat geholfen. Mich hatte in dem Kontext allerdings verwirrt, das --path nicht die root für --input setzt und alle Angaben mit --path damit relativ werden...

**Comment by andre-dietrich** [comment]
hidden files and folders starting with a dot are now excluded by default from packing.
